import React from 'react';
  

  // // app/layout.js or app/layout.jsx
// import { Montserrat, Nunito } from "next/font/google";
// import Header from "@/components/Header"
// import Footer from "@/components/Footer"
// // import FooterContent from "@/components/FooterContent"
// import "./globals.css";

// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// });

// const nunito = Nunito({
//   variable: "--font-nunito",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${montserrat.variable} ${nunito.variable} font-sans antialiased`}>
      
//         <Header />
//         {children}
//         <Footer />
//         {/* <FooterContent /> */}
//       </body>
//     </html>
//   );
// }
// app/layout.js// Add this
import { Montserrat, Nunito } from "next/font/google";
import Script from "next/script";
import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Trupeakhealth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
              <Script
  src="https://www.googletagmanager.com/gtag/js?id=G-4ZMFQQRJ76"
  strategy="afterInteractive"
/>
<Script id="google-analytics" strategy="afterInteractive">
  {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-4ZMFQQRJ76');
  `}
</Script>
<meta name="google-site-verification" content="tH7jgl8nZxdHL0l2FJowHAUkOxp2lZUaUpCTiulzhSU" />
      </head>

      <body
        className={`${montserrat.variable} ${nunito.variable} font-sans antialiased`}
      >
       <Navbar/>
        {children}
        <Footer />

        {/* Scroll Animation Script */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              document.addEventListener("DOMContentLoaded", function() {
                const observer = new IntersectionObserver((entries) => {
                  entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                      entry.target.classList.add("show");
                      observer.unobserve(entry.target);
                    }
                  });
                }, { threshold: 0.1 });

                document.querySelectorAll(".animate-on-scroll").forEach((el) => {
                  observer.observe(el);
                });
              });
            `,
          }}
        />
      </body>
    </html>
  );
}
